
export const WORLD_ASSET_KEYS = {
    WORLD_BACKGROUND:"WORLD_BACKGROUND",
    WORLD_FOREGROUND:"WORLD_FOREGROUND",
    WORLD_MAIN_LEVEL:"WORLD_MAIN_LEVEL",
    WORLD_COLLISION:"WORLD_COLLISION",
    WORLD_ENCOUNTER_ZONE:"WORLD_ENCOUNTER_ZONE",
} as const;


export const CHARACTER_ASSET_KEYS = {
    PLAYER:"PLAYER",
    NPC:"NPC",
} as const;

export type CHARACTER_ASSET_TYPES = keyof typeof CHARACTER_ASSET_KEYS;